---
- hosts: 127.0.0.1
  connection: local
  become: True
  vars:
    install_discord: True
    primary_user: ben
    primary_user_group: ben
  roles:
    - { role: common, tags: common }
    - { role: browser, tags: browser }
    - { role: terminal, tags: terminal }
    - { role: communication, tags: communication }
    - { role: design, tags: design }
    - { role: development, tags: development }
    - { role: devops, tags: devops }
    - { role: entertainment, tags: entertainment }
    - { role: writing, tags: writing }
