---
- hosts: 127.0.0.1
  connection: local
  become: True
  roles:
    - { role: common, tags: common }
    - { role: terminal, tags: terminal }
    - { role: development, tags: development }
    - { role: entertainment, tags: entertainment }