---
- hosts: 127.0.0.1
  connection: local
  become: True
  vars:
    install_chef: True
    install_chrome: True
    install_discord: False
    install_firefox: False
    install_pidgin: True
    primary_user: ben.overmyer
    primary_user_group: "domain users"
  vars_files:
    - vars/protolabs.yml
  roles:
    - { role: common, tags: common }
    - { role: browser, tags: browser }
    - { role: terminal, tags: terminal }
    - { role: communication, tags: communication }
    - { role: development, tags: development }
    - { role: devops, tags: devops }
