---
- hosts: 127.0.0.1
  connection: local
  become: True
  vars:
    install_chefdk: True
    install_discord: False
    install_firefox: False
    install_pidgin: True
    install_wire: False
    install_vivaldi: True
    primary_user: ben.overmyer
  roles:
    - { role: common, tags: common }
    - { role: browser, tags: browser }
    - { role: terminal, tags: terminal }
    - { role: communication, tags: communication }
    - { role: development, tags: development }
    - { role: devops, tags: devops }
