---
php_version: 7.1
nodejs_packages:
  - nodejs
  - npm
php_packages:
  - "php{{ php_version }}-fpm"
  - "php{{ php_version }}-cli"
  - "php{{ php_version }}-intl"
  - "php{{ php_version }}-json"
  - "php{{ php_version }}-mbstring"
  - "php{{ php_version }}-mcrypt"
  - "php{{ php_version }}-mysql"
  - "php{{ php_version }}-xml"
  - "php{{ php_version }}-zip"
