---
- name: Install Spotify key
  apt_key:
    keyserver: keyserver.ubuntu.com
    id: 0DF731E45CE24F27EEEB1450EFDC8610341D9410 931FF8E79F0876134EDDBDCCA87FF9DF48BF1C90
    state: present

- name: Add Spotify repository
  apt_repository:
    repo: deb http://repository.spotify.com stable non-free
    state: present

- name: Install Spotify
  apt:
    name: spotify-client
    state: present
    update_cache: True