---
- name: Download Go
  unarchive:
    remote_src: True
    src: https://dl.google.com/go/go1.11.linux-amd64.tar.gz
    dest: /usr/local/

- name: Add Go to PATH
  lineinfile:
    path: /etc/profile
    line: 'export PATH=$PATH:/usr/local/go/bin'
    state: present

- name: Create workspace directory
  file:
    path: "/home/{{ primary_user }}/go"
    state: directory
    owner: "{{ primary_user }}"
    group: "{{ primary_user_group }}"