---
- name: Download Go
  unarchive: 
    remote_src: True
    src: https://dl.google.com/go/go1.10.3.linux-amd64.tar.gz
    dest: /usr/local/

- name: Add Go to PATH
  lineinfile:
    path: /etc/profile
    line: 'export PATH=$PATH:/usr/local/go/bin'
    state: present

- name: Create workspace directory
  file:
    path: /home/ben/go
    state: directory
    owner: ben
    group: ben