---
- name: Install Visual Studio Code
  snap:
    name: code
    classic: True

- name: Add neovim apt repository
  apt_repository:
    repo: ppa:neovim-ppa/stable
    state: present

- name: Install neovim
  apt:
    name: neovim
    state: present
    update_cache: True
