---
- name: Create Source directory
  file:
    path: /home/ben/Source
    state: directory
    owner: ben
    group: ben
    
- name: Docker
  import_tasks: docker.yml
  tags: docker

- name: IDEs
  import_tasks: ide.yml

- name: Node.js
  import_tasks: nodejs.yml

- name: PHP
  import_tasks: php.yml

- name: Go
  import_tasks: go.yml