---
- name: Create Source directory
  file:
    path: "/home/{{ primary_user }}/Source"
    state: directory
    owner: "{{ primary_user }}"
    group: "{{ primary_user_group }}"

- name: Docker
  import_tasks: docker.yml
  tags: docker

- name: IDEs
  import_tasks: ide.yml

- name: Node.js
  import_tasks: nodejs.yml

- name: Go
  import_tasks: go.yml

- name: Install Hugo
  apt:
    deb: https://github.com/gohugoio/hugo/releases/download/v0.69.0/hugo_0.69.0_Linux-64bit.deb
