---
- name: Add PHP repository
  apt_repository:
    repo: ppa:ondrej/php
    state: present

- name: Update cache
  apt:
    update_cache: True

- name: Install PHP
  apt:
    name: "{{ php_packages }}"
    state: present

- name: Fetch Composer
  get_url:
    url: https://getcomposer.org/installer
    dest: /tmp/composer-installer

- name: Run Composer installer
  shell: php composer-installer
  args:
    chdir: /tmp/

- name: Move Composer binary to a global location
  shell: mv composer.phar /usr/local/bin/composer
  args:
    chdir: /tmp/