---
- name: Make zsh my default shell
  user:
    name: "{{ primary_user }}"
    shell: /usr/bin/zsh

- name: Run the Oh-My-Zsh installer
  become_user: "{{ primary_user }}"
  shell: sh -c "$(curl -fsSL https://raw.github.com/robbyrussell/oh-my-zsh/master/tools/install.sh)"

- name: Set the theme to pygmalion
  lineinfile:
    path: "/home/{{ primary_user }}/.zshrc"
    regexp: "^ZSH_THEME="
    line: 'ZSH_THEME="pygmalion"'

- name: Add my aliases file
  template:
    src: zsh-aliases.j2
    dest: "/home/{{ primary_user }}/.zshrc-aliases"
    owner: "{{ primary_user }}"
    group: "{{ primary_user_group }}"

- name: Add inclusion of aliases file to zshrc
  lineinfile:
    path: "/home/{{ primary_user }}/.zshrc"
    line: "source ~/.zshrc-aliases"
