---
- name: Update the apt cache
  apt:
    update_cache: True

- name: Install common stuff
  apt:
    name: "{{ item }}"
    state: present
  with_items:
    - apt-transport-https
    - ca-certificates
    - curl
    - zsh

- name: Install fonts
  import_tasks: fonts.yml

- name: Install Bitwarden
  shell: snap install bitwarden

- name: Chrome installation
  import_tasks: chrome.yml

- name: Install Slack
  shell: snap install slack --classic

- name: Install WordPress Desktop
  shell: snap install wordpress-desktop

- name: Krita installation
  import_tasks: krita.yml

- name: Dropbox installation
  import_tasks: dropbox.yml

- name: Install Discord
  shell: snap install discord

- name: Create Source directory
  file:
    path: /home/ben/Source
    state: directory
    owner: ben
    group: ben