---
- name: Update the apt cache
  apt:
    update_cache: True

- name: Install common stuff
  apt:
    name: "{{ item }}"
    state: present
  with_items:
    - apt-transport-https
    - ca-certificates
    - curl
    - zsh

- name: Install Flatpak
  import_tasks: flatpak.yml
  tags: flatpak

- name: Install fonts
  import_tasks: fonts.yml

- name: Install Bitwarden
  shell: snap install bitwarden

- name: Dropbox installation
  import_tasks: dropbox.yml
  when: install_dropbox

- name: Do SSH tasks
  import_tasks: ssh.yml